export const FETCH_CURRENCIES_STARTED = 'FETCH_CURRENCIES_STARTED';
export const FETCH_CURRENCIES_SUCCEDED = 'FETCH_CURRENCIES_SUCCEDED';
export const FETCH_CURRENCIES_FAILED = 'FETCH_CURRENCIES_FAILED';

export const ADD_TO_FAVOURITE = 'ADD_TO_FAVOURITE';
export const REMOVE_FROM_FAVOURITE = 'REMOVE_FROM_FAVOURITE';
export const REMOVE_ALL_FROM_FAVOURITE = 'REMOVE_ALL_FROM_FAVOURITE';